In [3]:
from scipy.stats import unitary_group
import lightcones.linalg as ll
import numpy as np

In [4]:
# probabilities
pi = [0.5, 0.3, 0.2]

# random basis
U = unitary_group.rvs(3)

# density matrix
rho = U @ np.diag(pi) @ U.T.conj()
rho = ll.make_hermitean(rho)

NameError: name 'll' is not defined

In [41]:
rho

In [30]:
import lightcones.linalg as ll

In [31]:
pi_, psi = ll.find_eigs_descending(rho)

ValueError: object arrays are not supported

In [20]:
pi_

array([0.5, 0.3, 0.2])

In [21]:
U

array([[-0.71320984+0.11490498j, -0.34817187+0.15597422j,
        -0.0532893 +0.57422749j],
       [ 0.60167581-0.33182055j, -0.20313573+0.23033763j,
         0.14770212+0.64167428j],
       [-0.07203499-0.02865077j,  0.81037348+0.3215955j ,
        -0.39146063+0.28393631j]])

In [22]:
psi

array([[ 0.7224067 +0.j        ,  0.38151226+0.j        ,
        -0.57669486-0.j        ],
       [-0.64679487+0.23189449j,  0.27955295-0.12716012j,
        -0.62528053+0.20636388j],
       [ 0.06656077+0.03974381j, -0.6080765 -0.62479742j,
        -0.31889429-0.36354873j]])

In [24]:
U @ psi.T.conj()

array([[-0.61732774-0.18863984j,  0.5226007 -0.25765732j,
        -0.12040822-0.47887843j],
       [ 0.27197681-0.52188301j, -0.512122  -0.31805149j,
        -0.27391333-0.46391004j],
       [ 0.48288219-0.06174949j,  0.52896299+0.13142934j,
        -0.67802463+0.07885984j]])

In [28]:
np.max(np.abs(U @ U.T.conj() - np.eye(3))[:])

np.float64(3.9472488203928496e-16)