In [ ]:
import lightcones.linalg as la
from lightcones.linalg import kron

U = 1
t = 0.05

#eps_cut = 0.00001

num_iterations = 100

m = 100
l = 5 + 1

# iteration 0: preparatory

# left subsystem

f = spinfull_fermions(l)

H_hopp = sum([sum([- t * (f.a_dag[s][i] @ f.a[s][i - 1] + f.a_dag[s][i - 1] @ f.a[s][i]) for s in range(2)]) for i in range(l)])
H_S = H_hopp + sum([U * f.n[0][i] @ f.n[1][i] for i in range(l)])

H_S_ = kron(H, f.eye)

a_S = f.a[:][-1]
a_S_dag = f.a_dag[:][-1]

a_S_ = kron(a_S, f.eye)
a_S_dag_ = kron(a_S_dag, f.eye)

# right subsystem

# fermion Hamiltonian is always even
H_E_ = kron(f.eye, H_S)

# a and a_dag are odd operators
a_E_ = kron(f.parity, a_S)
a_E_dag_ = kron(f.parity, a_S_dag)

# joint system Hamiltonian

H_SE = H_S_ + H_E_ - sum([t * (a_E_dag_[s] @ a_S_[s] + a_S_dag_[s] @ a_E_[s]) for s in range(2)])

# now start regular iterations

for i in range(num_iterations):

    # find ground state
    
    from scipy.sparse.linalg import eigsh
    E_GND, Psi_GND = eigsh(H_SE, k=1, which='SM')

    # partial trace

    r = reduce_bipartite(f.states.dimension, f.state_dimension, trace_over = 'R')

    rho = r(Psi_GND)

    # find eigenvalues sorted in ascending order

    pi, T = la.find_eigs_descending(rho)

    # keep only m largest eigenstates
    # columns are eigenstates
    T = T[:, : m] 

    # switch to the frame of revelant eigenstates
    T_dag = T.conj().T
    H_T = T_dag @ H_S @ T

    a_T = [T_dag @ a_S[s] @ T for s in range(2)]
    a_T_dag = [T_dag @ a_S_dag[s] @ T for s in range(2)]

    # new parity operator
    parity_T = T_dag @ f.parity @ T
    eye_T = la.eye(m)
    
    # add new site
    
    g = spinfull_fermions(1)
    
    # a and a_dag are odd operators
    a_S = kron(parity_T, g.a)
    a_S_dag = kron(parity_T, g.a_dag)
    
    a_T_ = kron(a_T, g.eye)
    a_T_dag_ = kron(a_T_dag, g.eye)
    
    # n is even operator
    n_ = kron(eye_T, g.n[:, 0])
        
    H_S = H_T - t * sum([a_S_dag[s] @ a_T_[s] + a_T_dag_[s] @ a_S[s] for s in range(2)]) + U * n_[0] @ n_[1]
    
    eye_T_ = kron(eye_T, g.eye)
    
    # left subsystem
    
    H_S_ = kron(H_S, eye_T_)
    
    a_S_ = kron(a_S, eye_T_)
    a_S_dag_ = kron(a_S_dag, eye_T_)

    # right subsystem

    parity_T_ = kron(parity_T, g.parity)

    # fermion Hamiltonian is always even
    H_E_ = kron(eye_T_, H_S)

    # a and a_dag are odd operators
    a_E_ = kron(parity_T_, a_S)
    a_E_dag_ = kron(parity_T_, a_S_dag)
    
    # joint system Hamiltonian

    H_SE = H_S_ + H_E_ - sum([t * (a_E_dag_[s] @ a_S_[s] + a_S_dag_[s] @ a_E_[s]) for s in range(2)])


    
    
    
    







In [ ]:
f = spinfull_fermions(n_modes)

f.states.state_at()
f.states.index_of()

f.vac()

f.up.a[i]
f.up.a_dag[i]

f.down.a[i]
f.down.a_dag[i]

f.a[s,i] # s = 0 (up) 1 (down)
f.a_dag[s, i]

f.n[s, i]

f.parity

f.zero

f.eye

In [ ]:
import numpy as np

array = np.empty((3, 3), dtype=object)
array[0, 0] = Node(...)

In [ ]:
import lightcones.linalg as la
from lightcones.linalg import kron

U = 1
t = 0.05

#eps_cut = 0.00001

num_iterations = 100

m = 100
l = 5 + 1

# iteration 0: preparatory

# left subsystem

f = spinfull_fermions(l)

H_hopp = sum([sum([- t * (f.a_dag[s, i] @ f.a[s, i - 1] + f.a_dag[s, i - 1] @ f.a[s, i]) for s in range(2)]) for i in range(l)])
H_S = H_hopp + sum([U * f.n[0, i] @ f.n[1, i] for i in range(l)])

H_S_ = kron(H, f.eye)

a_S = f.a[:, -1]
a_S_dag = f.a_dag[:, -1]

a_S_ = kron(a_S, f.eye)
a_S_dag_ = kron(a_S_dag, f.eye)

# right subsystem

H_E_ = kron(f.parity, H_S)

a_E_ = kron(f.parity, a_S)
a_E_dag_ = kron(f.parity, a_S_dag)

# joint system Hamiltonian

H_SE = H_S_ + H_E_ - sum([t * (a_E_dag_[s] @ a_S_[s] + a_S_dag_[s] @ a_E_[s]) for s in range(2)])

# now start regular iterations

for i in range(num_iterations):

    # find ground state
    
    from scipy.sparse.linalg import eigsh
    E_GND, Psi_GND = eigsh(H_SE, k=1, which='SM')

    # partial trace

    r = reduce_bipartite(f.states.dimension, f.state_dimension, trace_over = 'R')

    rho = r(Psi_GND)

    # find eigenvalues sorted in ascending order

    pi, T = la.find_eigs_descending(rho)

    # keep only m largest eigenstates
    # columns are eigenstates
    T = T[:, : m] 

    # switch to the frame of revelant eigenstates
    T_dag = T.conj().T
    H_T = T_dag @ H_S @ T

    a_T = [T_dag @ a_S[s] @ T for s in range(2)]
    a_T_dag = [T_dag @ a_S_dag[s] @ T for s in range(2)]

    # new parity operator
    parity_T = T_dag @ f.parity @ T
    eye_T = la.eye(m)
    
    # add new site
    
    g = spinfull_fermions(1)
    
    a_S = kron(parity_T, g.a)
    a_S_dag = kron(parity_T, g.a_dag)
    
    a_T_ = kron(a_T, g.eye)
    a_T_dag_ = kron(a_T_dag, g.eye)
    
    n_ = kron(parity_T, g.n[:, 0])
        
    H_S = H_T - t * sum([a_S_dag[s] @ a_T_[s] + a_T_dag_[s] @ a_S[s] for s in range(2)]) + U * n_[0] @ n_[1]
    
    eye_T_ = kron(eye_T, g.eye)
    
    # left subsystem
    
    H_S_ = kron(H_S, eye_T_)
    
    a_S_ = kron(a_S, eye_T_)
    a_S_dag_ = kron(a_S_dag, eye_T_)

    # right subsystem

    parity_T_ = kron(parity_T, g.parity)

    H_E_ = kron(parity_T_, H_S)

    a_E_ = kron(parity_T_, a_S)
    a_E_dag_ = kron(parity_T_, a_S_dag)
    
    # joint system Hamiltonian

    H_SE = H_S_ + H_E_ - sum([t * (a_E_dag_[s] @ a_S_[s] + a_S_dag_[s] @ a_E_[s]) for s in range(2)])


    
    
    
    







In [ ]:
from lightcones.linalg import kron

l = 5

f = spinfull_fermions(l)

H_hopp = sum([sum([- t * (f.a_dag[s, i] @ f.a[s, i - 1] + f.a_dag[s, i - 1] @ f.a[s, i]) for s in range(1)]) for i in range(l)])
H_S = H_hopp + sum([U * f.n[0, i] @ f.n[1, i] for i in range(l)])

s = spinfull_fermions(1)
#a_dag = kron(f.a_dag, s.eye)
#a = kron(f.a, s.eye)

a_dag = kron(f.a_dag[-1], s.eye)
a = kron(f.a[-1], s.eye)

b_dag = kron(f.parity, s.a_dag)
b = kron(f.parity, s.a)

n = kron(f.parity, s.n[:, 0])

H_S_prime = kron(H_s, s.eye) - t * (a_dag @ b + b_dag @ a) + U * n[0] @ n[1]

S_prime_parity = kron(f.parity, s.parity)
S_prime_eye = kron(f.eye, s.eye)

a_S = kron(a, S_prime_eye)
a_S_dag = kron(a_dag, S_prime_eye)

b_S = kron(S_prime_parity, a)
b_S_dag = kron(S_prime_parity, a_dag)

H_SE = kron(S_prime_parity, H_S_prime) + kron(H_S_prime, S_prime_eye) - t * (a_S_dag @ b_S + b_S_dag @ a_S)

from scipy.sparse.linalg import eigsh
E_GND, Psi_GND = eigsh(H_SR, k=1, which='SM')

# Как-то надо трейс взять по правой половине мод ...

rho_S_prime = trace(Psi_GND, range(l+1, 2*l+2)) #  ????
# что за space?
# наверное в качестве затравки надо общий блок из 2*l+2 мод взять?
rho_S_prime = space.trace(Psi_GND, range(l+1, 2*l+2))




 






In [1]:
import numpy as np
from scipy.sparse.linalg import eigsh
identity = np.eye(13)
eigenvalues, eigenvectors = eigsh(identity, k=6)

In [2]:
eigenvalues

array([1., 1., 1., 1., 1., 1.])

In [13]:
from scipy.sparse import diags
diagonals = [1, 2, 3, 4]
A = diags(diagonals, 0)
A.toarray()

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]])

In [14]:
eigenvalues, eigenvectors = eigsh(A, k=1, which='SM')

In [15]:
eigenvalues

array([1.])