In [10]:
import numpy as np
import lightcones.linalg as ll
import lightcones.models as lm
import lightcones.space as sp
import math
np.set_printoptions(precision=11)

In [17]:
l = lm.spinfull_fermions(2)
r = lm.spinfull_fermions(3)
bp = sp.bipartite(l.dimension, r.dimension)

A = 1 / math.sqrt(2) + 0.1
B = math.sqrt(1 - A**2)

psi = A * bp.kron(l.a_dag[0][0] @ l.vac(), r.a_dag[0][0] @ r.vac()) + \
    B * bp.kron(l.a_dag[1][0] @ l.vac(), r.a_dag[1][0] @ r.vac())
    
rho = bp.trace_out_R(psi)

pi, phi = ll.find_eigs_descending(rho)

pi

    

array([0.65142135624, 0.34857864376, 0.           , 0.           ,
       0.           , 0.           , 0.           , 0.           ,
       0.           , 0.           , 0.           , 0.           ,
       0.           , 0.           , 0.           , 0.           ])

In [24]:
len(pi)

16

In [19]:
A**2

0.6514213562373093

In [20]:
B**2

0.34857864376269065

In [21]:
l.a[0][0] @ phi[:, 0]

array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [22]:
l.a[1][0] @ phi[:, 1]

array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [23]:
l.a[0][1] @ phi[:, 1]

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [2]:
f = lm.spinfull_fermions(5)

In [3]:
U = 1
t = 0.05

In [4]:
H_hopp = sum([sum([- t * (f.a_dag[s][i] @ f.a[s][i - 1] + f.a_dag[s][i - 1] @ f.a[s][i]) for s in range(2)]) for i in range(5)])
H_S = H_hopp + sum([U * f.n[0][i] @ f.n[1][i] for i in range(5)])

In [5]:
H_S_ = H_S.todense()

In [6]:
e, v = ll.find_smallest_eigs(H_S_, 1)

In [7]:
e

array([-0.16681274756])

In [8]:
psi0 = np.zeros(f.dimension, dtype = complex)
psi0[0] = 1.0
psi0 = f.a_dag[0][3] @ f.a_dag[1][3] @ psi0

e2, v2 = ll.lancz_gnd_state(psi0, H_S, 10)

In [10]:
v3 = ll.lancz_recursion(psi0, H_S, 10)

In [11]:
v3

<Compressed Sparse Column sparse matrix of dtype 'float64'
	with 24 stored elements and shape (9, 9)>

In [12]:
v3.todense()

matrix([[ 1.           ,  0.1          ,  0.           ,  0.           ,
          0.           ,  0.           ,  0.           ,  0.           ,
          0.           ],
        [ 0.1          ,  0.           ,  0.11180339887,  0.           ,
          0.           ,  0.           ,  0.           ,  0.           ,
          0.           ],
        [ 0.           ,  0.11180339887,  0.39         ,  0.50734603576,
          0.           ,  0.           ,  0.           ,  0.           ,
          0.           ],
        [ 0.           ,  0.           ,  0.50734603576,  0.56384615385,
          0.15156131626,  0.           ,  0.           ,  0.           ,
          0.           ],
        [ 0.           ,  0.           ,  0.           ,  0.15156131626,
         -0.01258550205,  0.09059584351,  0.           ,  0.           ,
          0.           ],
        [ 0.           ,  0.           ,  0.           ,  0.           ,
          0.09059584351,  0.25662647883,  0.41854017073,  0.       

In [1]:
v2

NameError: name 'v2' is not defined

In [9]:
tol = 1e-10
assert abs(np.vdot(v, v2) - 1.0) < tol