In [2]:
!which python3

/home/evgenii/condmat/lightcones_2024/infinite_dmrg.3/lightcones/venv/bin/python3


In [3]:
import sys
print(sys.path)

['/home/evgenii/intel/oneapi/advisor/2023.0.0/pythonapi', '/home/evgenii/anaconda3/lib/python311.zip', '/home/evgenii/anaconda3/lib/python3.11', '/home/evgenii/anaconda3/lib/python3.11/lib-dynload', '', '/home/evgenii/condmat/lightcones_2024/infinite_dmrg.3/lightcones/venv/lib/python3.11/site-packages']


In [1]:
import lightcones

In [2]:
import numpy as np
import pytest

import lightcones.space as sp

tol = 1e-10

def test_fermions():
    
    # exception throwing
    
    s = sp.states(3, bounding_condition=sp.bounding_condition.more_than_in_total(2))
    with pytest.raises(ValueError) as exc_info:
        f = sp.fermions(s)
    assert str(exc_info.value) == "Using more than singly occupied states to construct fermionic operators"
    
    #
    s = sp.states(3, bounding_condition=sp.bounding_condition.more_than_singly_occupied())
    f = sp.fermions(s)
    
    # vac
    vac = f.vac()
    expected = [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]
    assert np.allclose(vac, expected, atol=tol), \
        f"vac"
    
    # eye
    
    m = f.eye
    data = [1., 1., 1., 1., 1., 1., 1., 1.]
    indices = [0, 1, 2, 3, 4, 5, 6, 7]
    indptr = [0, 1, 2, 3, 4, 5, 6, 7, 8]
    
    assert np.allclose(m.data, data, atol=tol), \
        f"data for eye"
    assert np.array_equal(m.indices, indices), \
        f"indices for eye"
    assert np.array_equal(m.indptr, indptr), \
        f"indptr for eye"
        
    # zero
    
    m = f.zero
    data = []
    indices = []
    indptr = [0, 0, 0, 0, 0, 0, 0, 0, 0]
    
    assert np.allclose(m.data, data, atol=tol), \
        f"data for zero"
    assert np.array_equal(m.indices, indices), \
        f"indices for zero"
    assert np.array_equal(m.indptr, indptr), \
        f"indptr for zero"
    
    # a[0]
    m1 = f.a[0]
    
    data = [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]
    indices = [0, 1, 2, 3]
    indptr = [0, 0, 0, 0, 0, 1, 2, 3, 4]
    
    assert np.allclose(m1.data, data, atol=tol), \
        f"data for a[0]"
    assert np.array_equal(m1.indices, indices), \
        f"indices for a[0]"
    assert np.array_equal(m1.indptr, indptr), \
        f"indptr for a[0]"
        
    # a[1]
    
    m2 = f.a[1]
    
    data = [1.+0.j,  1.+0.j, -1.+0.j, -1.+0.j]
    indices = [0, 1, 4, 5]
    indptr = [0, 0, 0, 1, 2, 2, 2, 3, 4]
    
    assert np.allclose(m2.data, data, atol=tol), \
        f"data for a[1]"
    assert np.array_equal(m2.indices, indices), \
        f"indices for a[1]"
    assert np.array_equal(m2.indptr, indptr), \
        f"indptr for a[1]"
    
    # a[2]
    
    m3 = f.a[2]
    
    data = [1.+0.j, -1.+0.j, -1.+0.j,  1.+0.j]
    indices = [0, 2, 4, 6]
    indptr = [0, 0, 1, 1, 2, 2, 3, 3, 4]
    
    assert np.allclose(m3.data, data, atol=tol), \
        f"data for a[1]"
    assert np.array_equal(m3.indices, indices), \
        f"indices for a[1]"
    assert np.array_equal(m3.indptr, indptr), \
        f"indptr for a[1]"
    
    # a_dag[0]
    
    m1 = f.a_dag[0]
    
    data = [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]
    indices = [4, 5, 6, 7]
    indptr = [0, 1, 2, 3, 4, 4, 4, 4, 4]
    
    assert np.allclose(m1.data, data, atol=tol), \
        f"data for a_dag[0]"
    assert np.array_equal(m1.indices, indices), \
        f"indices for a_dag[0]"
    assert np.array_equal(m1.indptr, indptr), \
        f"indptr for a_dag[0]"
    
    # a_dag[1]
    
    m2 = f.a_dag[1]
    
    data = [1.+0.j,  1.+0.j, -1.+0.j, -1.+0.j]
    indices = [2, 3, 6, 7]
    indptr = [0, 1, 2, 2, 2, 3, 4, 4, 4]
    
    assert np.allclose(m2.data, data, atol=tol), \
        f"data for a_dag[1]"
    assert np.array_equal(m2.indices, indices), \
        f"indices for a_dag[1]"
    assert np.array_equal(m2.indptr, indptr), \
        f"indptr for a_dag[1]"
    
    # a_dag[2]
    
    m3 = f.a_dag[2]
    
    data = [1.+0.j, -1.+0.j, -1.+0.j,  1.+0.j]
    indices = [1, 3, 5, 7]
    indptr = [0, 1, 1, 2, 2, 3, 3, 4, 4]
    
    assert np.allclose(m3.data, data, atol=tol), \
        f"data for a_dag[2]"
    assert np.array_equal(m3.indices, indices), \
        f"indices for a_dag[2]"
    assert np.array_equal(m3.indptr, indptr), \
        f"indptr for a_dag[2]"
    
    
    

In [4]:
s = sp.states(3, bounding_condition=sp.bounding_condition.more_than_in_total(2))

In [5]:
f = sp.fermions(s)

ValueError: Using more than singly occupied states to construct fermionic operators

In [3]:
test_fermions()

IndexError: list index out of range

In [1]:
from lightcones.linalg import as_column_vector

In [3]:
import numpy as np
n = np.array([0, 1, 2])

In [4]:
ket = as_column_vector(n)

In [5]:
ket

array([[0],
       [1],
       [2]])

In [6]:
ket2 = as_column_vector(ket)

In [7]:
ket2

array([[[0]],

       [[1]],

       [[2]]])

In [3]:
import lightcones.space as sp
import numpy as np

In [4]:
j = 3
s1 = sp.states(1, bounding_condition=sp.bounding_condition.more_than_n_occupied(2 * j))
q = sp.spins(j, s1)
    
s2 = sp.states(2, bounding_condition=sp.bounding_condition.more_than_in_total(3))
b = sp.bosons(s2)
    
bp = sp.bipartite(q.states.dimension, b.states.dimension)

psi = np.zeros(bp.dimension, dtype = complex)
bp.trace_out_L(psi)

KeyError: (7, 0)

In [6]:
print(bp.L_dimension)
print(bp.R_dimension)

7
10


In [5]:
print(q.states.dimension)
print(b.states.dimension)

7
10


In [2]:
import math
import lightcones.space as sp
import lightcones.linalg as ll

In [5]:
j = 3
s1 = sp.states(1, bounding_condition=sp.bounding_condition.more_than_n_occupied(2 * j))
q = sp.spins(j, s1)

s2 = sp.states(2, bounding_condition=sp.bounding_condition.more_than_in_total(3))
b = sp.bosons(s2)

bp = sp.bipartite(q.states.dimension, b.states.dimension)

psi = bp.vector_with((0, b.states.index_of((0, 0)))) / math.sqrt(3.0) \
    + bp.vector_with((1, b.states.index_of((1, 0)))) / math.sqrt(3.0) \
    + bp.vector_with((2, b.states.index_of((1, 1)))) / math.sqrt(3.0)
    
rho_actual = bp.trace_out_R(psi)

rho_expected = \
    ll.projection_to(q.states.vector_with((0,))) / 3.0 + \
    ll.projection_to(q.states.vector_with((1,))) / 3.0 + \
    ll.projection_to(q.states.vector_with((2,))) / 3.0

In [9]:
import numpy as np
tol = 1e-10
assert np.allclose(rho_actual, rho_expected, atol=tol), \
    f"rho does not match"

In [4]:
q.states.all_states

[(0,), (1,), (2,), (3,), (4,), (5,), (6,)]

In [9]:
import numpy as np
arr1 = np.zeros(1)
arr1[0] = 1
arr2 = np.zeros(1)
arr2[0] = 2
arr3 = np.zeros(1)
arr3[0] = 3

In [11]:
arr1

array([1.])

In [12]:
arr2

array([2.])

In [10]:
arr3

array([3.])

In [13]:
arr1, arr2, arr3 = arr2, arr3, arr1

In [14]:
arr1

array([2.])

In [15]:
arr2

array([3.])

In [16]:
arr3

array([1.])

In [1]:
import lightcones.linalg as ll
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 1, 1, 1])
H = ll.tridiag(a, b)

In [6]:
e, v = ll.find_smallest_eigs(H.todense(), 1)

In [7]:
e

array([0.25384245])

In [8]:
psi0 = np.array([1, 0, 0, 0, 0])

In [9]:
e, v = ll.lancz_gnd_state(psi0, H, 5)

In [10]:
e

array([0.25384245])

In [11]:
e, v = ll.lancz_gnd_state(psi0, H, 4)

In [12]:
e

array([0.25471876])

In [21]:
H.todense()

matrix([[1, 1, 0, 0, 0],
        [1, 2, 1, 0, 0],
        [0, 1, 3, 1, 0],
        [0, 0, 1, 4, 1],
        [0, 0, 0, 1, 5]])

In [22]:
psi0 = np.array([1, 0, 0, 0, 0])

In [25]:
ll.lancz(psi0, H, 5).todense()

matrix([[1., 1., 0., 0., 0.],
        [1., 2., 1., 0., 0.],
        [0., 1., 3., 1., 0.],
        [0., 0., 1., 4., 1.],
        [0., 0., 0., 1., 5.]])

In [3]:
import lightcones.models as lm

In [4]:
f = lm.spinfull_fermions(5)


In [5]:
U = 1
t = 0.05

In [6]:
H_hopp = sum([sum([- t * (f.a_dag[s][i] @ f.a[s][i - 1] + f.a_dag[s][i - 1] @ f.a[s][i]) for s in range(2)]) for i in range(5)])
H_S = H_hopp + sum([U * f.n[0][i] @ f.n[1][i] for i in range(5)])

In [7]:
H_S_ = H_S.todense()

In [8]:
e, v = ll.find_smallest_eigs(H_S_, 1)

In [36]:
v.shape

(1024, 1)

In [15]:
v[:]

(1024, 1)

In [9]:
np.set_printoptions(precision=11)
e

array([-0.16681274756])

In [10]:
N = sum([f.n[0][i] + f.n[1][i] for i in range(5)])

In [11]:
np.vdot(v, N @ v)

np.complex128(2.0000000000000004+0j)

In [14]:
np.set_printoptions(precision=11)
psi0 = np.zeros(f.dimension, dtype = complex)
psi0[0] = 1.0
psi0 = f.a_dag[0][3] @ f.a_dag[1][3] @ psi0

e2, v2 = ll.lancz_gnd_state(psi0, H_S, 10)

e2

array([-0.16681274756])

In [13]:
v2

<Compressed Sparse Column sparse matrix of dtype 'float64'
	with 24 stored elements and shape (9, 9)>

In [14]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 1, 1, 1])
H = ll.tridiag(a[:1], b[:0])

In [15]:
H.todense()

matrix([[1]])

In [31]:
np.vdot(v, v2)

ValueError: cannot reshape array of size 9 into shape (1024,)