In [3]:
import numpy as np
import pytest
import lightcones.space as sp
from lightcones.models import top

In [10]:
t = top(11)

In [11]:
j_m = t.j_m

In [12]:
j_m.data

array([ 4.69041576+0.j,  6.4807407 +0.j,  7.74596669+0.j,  8.71779789+0.j,
        9.48683298+0.j, 10.09950494+0.j, 10.58300524+0.j, 10.95445115+0.j,
       11.22497216+0.j, 11.40175425+0.j, 11.48912529+0.j, 11.48912529+0.j,
       11.40175425+0.j, 11.22497216+0.j, 10.95445115+0.j, 10.58300524+0.j,
       10.09950494+0.j,  9.48683298+0.j,  8.71779789+0.j,  7.74596669+0.j,
        6.4807407 +0.j,  4.69041576+0.j])

In [13]:
j_m.indices

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21], dtype=int32)

In [14]:
j_m.indptr

array([ 0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22], dtype=int32)

In [7]:
t.states.dimension

3